[Interface]
PrivateKey = <NAS_PRIVATE_KEY>
Address = 10.0.1.2/32
PostUp = sysctl -w net.ipv4.ip_forward=1; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o br0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o br0 -j MASQUERADE

[Peer]
PublicKey = 0i7YEi/u8U4M8LNfMxLh9vyYsexvIB048kyOlpUApW0=
Endpoint = 39.107.225.19:50300
AllowedIPs = 10.0.1.0/24
PersistentKeepalive = 25
